@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVlZmVmM2NmZjY2YTdlNDQ1NWU2NGI1YyIsIm5hbWUiOiJtYWxhdiIsImlhdCI6MTU5MzkzMTYwOCwiZXhwIjoxNTk0MDE4MDA4fQ.gNu4wBzaKubCrz0ygUj0PnnVFmXKkQjpmE-AbT6Thdo

POST http://localhost:6969/auth/register
Content-Type: application/json

{
    "name": "malav",
    "email": "patelmalav@protonmail.me",
    "password": "malavpatel"
}

###

POST http://localhost:6969/auth/login
Content-Type: application/json

{
    "email": "patelmalav64@gmail.com",
    "password": "malavpatel"
}

###

GET http://localhost:6969/todos
Authorization: Bearer {{jwtToken}}

###

GET http://localhost:6969/todos/174
Authorization: Bearer {{jwtToken}}

###

POST http://localhost:6969/todos
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

[
    {
        "name": "fuck list",
        "task": [
            {
                "title": "parinda",
                "completed": true
            }
        ]
    }
]

###

PUT http://localhost:6969/todos/555
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "name": "fuck list",
    "task": [
        {
            "title": "parinda",
            "completed": true
        }
    ]
}
###

DELETE  http://localhost:6969/todos/10229
Authorization: Bearer {{jwtToken}}
